module.exports = {
	'wrap': 'wrap',
	'no': 'no-wrap',
	'no-wrap': 'no-wrap',
	'start': 'flex-start',
	'flex-start': 'flex-start',
	'end': 'flex-end',
	'flex-end': 'flex-end',
	'center': 'center',
	'between': 'space-between',
	'space-between': 'space-between',
	'around': 'space-around',
	'space-around': 'space-around',
	'evenly': 'space-evenly',
	'space-evenly': 'space-evenly',
	'stretch': 'stretch',
}